import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Filter, ArrowRight, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../../lib/api';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Select } from '../../components/ui/Select';
import { PriorityBadge, AlertStatusBadge } from '../../components/ui/StatusBadge';
import { MaintenanceAlert } from '@maintenance/shared';

export const AlertListPage: React.FC = () => {
  const [priorityFilter, setPriorityFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  const { data: response, isLoading } = useQuery<{ data: MaintenanceAlert[] }>({
    queryKey: ['alerts-list', priorityFilter, statusFilter],
    queryFn: () => {
      const params = new URLSearchParams();
      if (priorityFilter) params.set('priority', priorityFilter);
      if (statusFilter) params.set('status', statusFilter);
      return api.get(`/alerts?${params.toString()}`) as any;
    },
  });

  const alerts = response?.data || [];

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-white tracking-tight">Maintenance Alert Queue</h2>
        <p className="text-xs text-slate-400">
          Prioritized operational breaches generated by automated parameter evaluation.
        </p>
      </div>

      {/* Filter bar */}
      <Card className="p-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            options={[
              { value: '', label: 'All Priorities' },
              { value: 'CRITICAL', label: 'CRITICAL' },
              { value: 'HIGH', label: 'HIGH' },
              { value: 'MEDIUM', label: 'MEDIUM' },
            ]}
          />
          <Select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            options={[
              { value: '', label: 'All Alert Statuses' },
              { value: 'OPEN', label: 'OPEN (Requires Acknowledgment)' },
              { value: 'ACKNOWLEDGED', label: 'ACKNOWLEDGED (Ready for Work Order)' },
              { value: 'CONVERTED_TO_WORK_ORDER', label: 'CONVERTED_TO_WORK_ORDER' },
              { value: 'RESOLVED', label: 'RESOLVED' },
            ]}
          />
        </div>
      </Card>

      {/* Alerts Table */}
      <Card className="p-0 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="text-[11px] uppercase tracking-wider text-slate-400 bg-industrial-900/80 border-b border-industrial-800">
              <tr>
                <th className="px-5 py-3 font-medium">Alert ID</th>
                <th className="px-5 py-3 font-medium">Equipment Asset</th>
                <th className="px-5 py-3 font-medium">Parameter</th>
                <th className="px-5 py-3 font-medium">Reading / Threshold</th>
                <th className="px-5 py-3 font-medium">Breach %</th>
                <th className="px-5 py-3 font-medium">Priority</th>
                <th className="px-5 py-3 font-medium">Status</th>
                <th className="px-5 py-3 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-industrial-800/60">
              {isLoading ? (
                <tr>
                  <td colSpan={8} className="px-5 py-8 text-center text-slate-500">
                    Loading alert queue...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-5 py-8 text-center text-slate-500">
                    No alerts found for current filters.
                  </td>
                </tr>
              ) : (
                alerts.map((a) => (
                  <tr key={a.id} className="hover:bg-industrial-800/40 transition-colors">
                    <td className="px-5 py-3.5 font-bold font-mono text-slate-100">{a.alert_id}</td>
                    <td className="px-5 py-3.5 font-semibold text-slate-200">
                      {a.equipment?.name || a.equipment_id}
                    </td>
                    <td className="px-5 py-3.5 text-slate-300">{a.parameter?.name || 'Parameter'}</td>
                    <td className="px-5 py-3.5 text-slate-300 font-mono">
                      <span className="font-bold text-red-400">{a.current_value}</span> /{' '}
                      <span className="text-slate-400">{a.threshold_value}</span> {a.parameter?.unit}
                    </td>
                    <td className="px-5 py-3.5 font-bold text-amber-400">+{a.breach_percentage}%</td>
                    <td className="px-5 py-3.5">
                      <PriorityBadge priority={a.priority} />
                    </td>
                    <td className="px-5 py-3.5">
                      <AlertStatusBadge status={a.status} />
                    </td>
                    <td className="px-5 py-3.5 text-right">
                      <Link
                        to={`/alerts/${a.id}`}
                        className="inline-flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 font-semibold"
                      >
                        Inspect <ArrowRight className="w-3.5 h-3.5" />
                      </Link>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};
